version: '3.6'
networks:
  kbase-dev:
    name: kbase-dev
services:
  doirequest:
    build:
      context: .
      dockerfile: Dockerfile

    image: kbase/doirequest:dev

    container_name: DOIRequest
    dns: 8.8.8.8
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ./src:/kb/module/src
      - ./dev/work:/kb/module/work
      - ./templates:/kb/module/templates
      - ./data:/kb/module/data
      - ./scripts:/kb/module/scripts
    networks:
      - kbase-dev
    ports:
      - "5002:5000"
    environment:
      - KBASE_ENDPOINT=${KBASE_ENDPOINT}
      - KBASE_SECURE_CONFIG_PARAM_IS_DYNAMIC_SERVICE=${KBASE_SECURE_CONFIG_PARAM_IS_DYNAMIC_SERVICE}
